### ISSUE TITLE
CFLAGS etc.

### ISSUE THREAD

**Issue by vcunat** [cloudflare/lua-aho-corasick#12] opened 2018-11-22 17:43 UTC
When I see things like `-msse4.1` in `./Makefile`, I wonder whether you intend the master branch of this repo for general-purpose usage, e.g. ending up in distribution packages.  Should I make similar changes in a fork or shall we generalize it directly here, perhaps in a way that you might keep injecting such flags somehow?

Currently the binaries will end up in knot-resolver packages _with_ these flags (even on ARM :)  I suspect this will be a real problem for x86 systems without SSE 4.1, and most users surely won't notice a significant difference in speed if we drop these flags.  (I understand _you_ might notice the difference on CloudFlare servers.)

**Comment by vcunat** [comment] 2018-11-22 17:45
There are also other weird things I see, e.g. passing `CFLAGS` to c++ compiler, etc. so I'd probably look at these as well.

**Comment by vcunat** [comment] 2018-12-10 18:00
OK, I created some implementation instead of just talking: https://github.com/cloudflare/lua-aho-corasick/pull/13

**Comment by pspacek** [comment] 2018-12-13 14:39
@vavrusa Could you please poke someone to get fixes merged? Thanks!

**Comment by vcunat** [comment] 2018-12-14 19:55
Or just get some "authoritative" opinion; it's not a big deal for us to maintain a fork, but it would seem better if we can agree on one common version.

**Comment by jdesgats** [comment] 2018-12-17 18:04
Hey, sorry for the late answer. It turns out we already fixed this issue internally, I pushed the corresponding patches in #14

**Comment by vcunat** [comment] 2018-12-18 09:02
Well, this is a misunderstanding between us &ndash; my concern was that _by default_ the code should work on any CPU of the given architecture.  Old example: x86_64 does not guarantee sse4.1; new example: aarch64 does not guarantee the CRC instructions.  I actually _suspect_ that [our device](https://mox.turris.cz/en/specification) which already runs this code doesn't have CRC, but I've been primarily concerned about compatibility from the point of view of generic packaging for unix-like systems.

**Comment by jdesgats** [comment] 2019-01-09 17:47
You are right, we should not hard-code CPU-specific compile flags (being amd64 or ARM). I guess that a proper configure script or cmake file could detect them automatically, but we don't have that so far so your PR is the best way forward.

Sorry again, I ogt busy on many other things and I needed to check where this module is used in our internal repos in order to not have any regressions.

**Comment by jdesgats** [comment] 2019-01-09 17:49
Solved by merging #13.

**Closed by jdesgats** 2019-01-09 17:49 UTC
